job_name: Qwen3-8B_NVFP4_DEFAULT_CFG
pipeline:
  skip: false
  allow_to_fail: false
  note:

  task_0:
    script: services/megatron-lm/quantize/quantize.sh
    args:
      - --calib-dataset-path-or-name /hf-local/abisee/cnn_dailymail
      - --calib-size 32
    environment:
      - MLM_MODEL_CFG: Qwen/Qwen3-8B
      - QUANT_CFG: NVFP4_DEFAULT_CFG
      - TP: 4
    slurm_config:
      _factory_: "slurm_factory" # oci_hsg_slurm_factory
      nodes: 1
      ntasks_per_node: 4
      gpus_per_node: 4

